version: '3.8'

volumes:
  postgres-data:
    driver: local
  superset-db:
    driver: local
    
services:
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:v21.11.15
    command:
      - redpanda start
      - --smp 1
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
        
  datareceiverservice:
    build:
      context: .
      dockerfile: DataReceiverService/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
    depends_on:
      - redpanda
        
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/data/postgres
      - ./pg_initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=analytics_database
      - POSTGRES_USER=analytics_rw_user
      - POSTGRES_PASSWORD=analytics_rw_user_password
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
        
  datawriterservice:
    build:
      context: .
      dockerfile: DataWriterService/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
    depends_on:
      - redpanda
      - postgres
        
  superset:
    image: apache/superset
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SUPERSET_SECRET_KEY=unsecure_key_but_it_is_fine_for_testing
    volumes:
      - superset-db:/home/superset/.superset

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  superset-worker:
    image: apache/superset
    command: superset worker
    depends_on:
      - superset
      - redis
    environment:
      - SUPERSET_DB_URI=postgresql+psycopg2://analytics_rw_user:analytics_rw_user_password@postgres:5432/analytics_database
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - superset-db:/home/superset/.superset