version: '3.8'
services:
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:v21.11.15
    command:
      - redpanda start
      - --smp 1
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
        
  datareceiverservice:
    build:
      context: ./DataReceiverService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081